### ISSUE TITLE
Provide C/Java Code for binary search

### ISSUE THREAD

**Issue by gdsccom** [gdsccom/C-Java#3]
Provide the code for binary search in either C language or Java language.

**Comment by ShikhaDhiman1** [comment]
I want to contribute to this issue. Kindly assign this to me.

**Comment by sumit15jha** [comment]
I want to contribute too

**Comment by sumit15jha** [comment]
This issue also assigned to @ShikhaDhiman1 .

**Comment by gdsccom** [comment]
This issue is assigned to @ShikhaDhiman1

**Comment by gdsccom** [comment]
@sumit15jha you can also provide solution for this issue in C language only.

**Comment by sumit15jha** [comment]
Ok assign me this too @gdsccom

**Comment by gdsccom** [comment]
Ok, assigned to @sumit15jha for C language.

**Comment by gdsccom** [comment]
Thanks @sumit15jha and @ShikhaDhiman1 for your contribution.
