### ISSUE TITLE
Code for Count Sort.

### ISSUE THREAD

**Issue by gdsccom** [gdsccom/C-Java#30]
Write a programme for count sort in any language.

**Comment by shubhambhugra** [comment]
Kindly assign me this issue.

**Comment by gdsccom** [comment]
Assigned to @shubhambhugra

**Comment by gdsccom** [comment]
issue closed

**Comment by Gourav2001kumar** [comment]
Assign me this issue for C language

**Comment by gdsccom** [comment]
Ok, assigned to @Gourav2001kumar
