### ISSUE TITLE
Code for reversing a linked list

### ISSUE THREAD

**Issue by gdsccom** [gdsccom/C-Java#34]
Write a program for reversing a linked list in any language.

**Comment by shubhambhugra** [comment]
Kindly assign me this issue

**Comment by gdsccom** [comment]
Assigned to @shubhambhugra

**Comment by gdsccom** [comment]
Now, need code in other than Java language

**Comment by Gourav2001kumar** [comment]
Assign me this issue for C language.

**Comment by gdsccom** [comment]
Ok assigned to @Gourav2001kumar

**Comment by JatinBawne** [comment]
Hello sir, if you need code in C++ or in Python, kindly assign it to me
