### ISSUE TITLE
Provide C/Java Code for matrix multiplication

### ISSUE THREAD

**Issue by gdsccom** [gdsccom/C-Java#4]
Provide code for matrix multiplication in C language or Java language.

**Comment by ShikhaDhiman1** [comment]
I want to contribute to this issue. Kindly assign this to me.

**Comment by sumit15jha** [comment]
I want to contribute. Kindly assign me this issue

**Comment by gdsccom** [comment]
Ok @ShikhaDhiman1 you have been assigned this issue

**Comment by gdsccom** [comment]
@sumit15jha if you want you can contribute too in this issue but in C language only.

**Comment by sumit15jha** [comment]
Ok I would like to contribute

**Comment by gdsccom** [comment]
@sumit15jha assigned to you too Kindly provide solution in C language.

**Comment by gdsccom** [comment]
Thank you @ShikhaDhiman1 and @sumit15jha for your contribution.
